spring.application.name=talentnova
server.port=9090

# DATABASE H2
spring.datasource.url=jdbc:h2:mem:talentnovadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

# JPA & SQL Initialization
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=always

#API
api.peru.dev=https://api.apiperu.dev/ruc
api.peru.dev.token=22658|MwSHGR4z0zYezXSiwlo7msOXzj2JyYDNPBo06XPB66057e16

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yire2005lol@gmail.com
spring.mail.password=vsep vuhq sfuu ohup
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CONSOLE WEB H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#HIBERNATE
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl